# Description

This work is based on learning the basics of working with the Numerical Python library (indexing, mathematical operations, data types, methods).

# Tasks

In [1]:
import numpy as np
import sys
import warnings

In [2]:
warnings.filterwarnings('ignore')

Task 1. A function that creates a 1D array of numbers from 0 to 9.

In [3]:
def create_1D_array(x: int):
    result = np.array([y for y in range(x+1)])
    return result

In [4]:
create_1D_array(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Task 2. A function that creates a 3 × 3 numpy array consisting of all True’s.

In [5]:
def create_3D_array():
    result = np.full((3,3), True)
    return result

In [6]:
create_3D_array()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Task 3. A function that returns all odd numbers from an array. 

In [7]:
def get_odd(array_):
    return array_[array_%2 == 1]

In [8]:
get_odd(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([1, 3, 5, 7, 9])

Task 4. A function that replaces all odd numbers in an array by -1.

In [9]:
def replace_odd(array_):
    array_[array_%2 == 1] = -1
    return array_

In [10]:
replace_odd(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Task 5. A function that replaces all odd numbers with -1 without changing the array (where).

In [11]:
def replace_odd_where(array_):
    return np.where(array_%2 == 1, -1, array_)

In [12]:
replace_odd_where(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Task 6. A function that converts 1D array to 2D array with 2 rows (use reshape). 

In [13]:
def convert_1D_to_2D(array_):
    return array_.reshape((2, len(array_)//2))

In [14]:
convert_1D_to_2D(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Task 7. Make up arrays a and b vertically.

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Task 8. Make up arrays a and b horizontally. 

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Task 9. A function that makes the next pattern without using hard code.

In [17]:
def create_pattern(array_):
    start = np.tile(array_, (3, 1)).T.reshape(9, )
    end = np.tile(array_, 3)
    return np.concatenate((start, end), axis=None)

In [18]:
pattern = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1, 2, 3])

create_pattern(a)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Task 10. Return the same values between arrays a and b.

In [19]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.intersect1d(a, b)

array([2, 4])

Task 11. Return values from array a that are not in array b.

In [20]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

Task 12. A function that returns the indices of elements that match in two arrays. 

In [21]:
def get_match_indices(a, b):
    return np.where(a == b)

In [22]:
get_match_indices(np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]), np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]))

(array([1, 3, 5, 7]),)

Task 13. Return all values that are greater than 5 and less than or equal to 10.

In [23]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[np.logical_and(a>5, a<=10)]

array([ 6,  9, 10])

Task 14. Convert a maxx function that works with two scalar values so that it can work with arrays.

In [24]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

In [25]:
vector_maxx = np.vectorize(maxx, otypes=[float])
vector_maxx(np.array([5, 7, 9, 8, 6, 4, 5]), np.array([6, 3, 4, 8, 9, 7, 1]))

array([6., 7., 9., 8., 9., 7., 5.])

Task 15. A function that swaps columns 1 and 2.

In [26]:
def swap_columns(array_, first_idx, second_idx):
    array_[:, [first_idx, second_idx]] = array_[:, [second_idx, first_idx]]
    return array_

In [27]:
swap_columns(np.arange(9).reshape(3, 3), 1, 2)

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

Task 16. Create a 2D array of size 5x3 which consists of arbitrary decimal numbers in the range between 5 and 10.

In [28]:
np.random.uniform(5, 10, [5, 3])

array([[5.7370295 , 9.68085149, 5.08879883],
       [8.26560367, 6.64863478, 7.80901373],
       [5.83066787, 9.67194646, 5.93546304],
       [5.47282873, 5.21636798, 9.92598059],
       [5.38750638, 5.60463284, 6.41952401]])

Task 17. Display only 3 decimal places in the numpy array.

In [29]:
np.set_printoptions(precision=3)
np.random.random((5, 3))

array([[0.473, 0.966, 0.169],
       [0.151, 0.498, 0.08 ],
       [0.885, 0.795, 0.151],
       [0.22 , 0.273, 0.942],
       [0.485, 0.566, 0.771]])

Task 18. Print numpy array by changing scientific notation to engineering (1e-01 -> 0.1).

In [30]:
np.set_printoptions(precision=6, suppress=True)
np.random.random([3, 3])/1e3

array([[0.000141, 0.000395, 0.000815],
       [0.000843, 0.000485, 0.000105],
       [0.000603, 0.000725, 0.000013]])

Task 19. Print the entire numpy array without trimming the values.

In [31]:
np.set_printoptions(threshold=sys.maxsize)
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Task 20. Import the iris dataset keeping the text intact.

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Task 21. Get the text for the species column.

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = [row[4] for row in iris_1d]