# Description

This work is based on learning the basics of working with the Numerical Python library.

# Tasks

In [1]:
import numpy as np

Task 1. A function that creates a 1D array of numbers from 0 to 9.

In [2]:
def create_1D_array(x: int):
    result = np.array([y for y in range(x+1)])
    return result

In [3]:
create_1D_array(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Task 2. A function that creates a 3 × 3 numpy array consisting of all True’s.

In [4]:
def create_3D_array():
    result = np.full((3,3), True)
    return result

In [5]:
create_3D_array()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Task 3. A function that returns all odd numbers from an array. 

In [6]:
def get_odd(array_):
    return array_[array_%2 == 1]

In [7]:
get_odd(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([1, 3, 5, 7, 9])

Task 4. A function that replaces all odd numbers in an array by -1.

In [8]:
def replace_odd(array_):
    array_[array_%2 == 1] = -1
    return array_

In [9]:
replace_odd(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Task 5. A function that replaces all odd numbers with -1 without changing the array (where).

In [10]:
def replace_odd_where(array_):
    return np.where(array_%2 == 1, -1, array_)

In [11]:
replace_odd_where(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])