# Description

This work describes the basics of working in the PyTorch library (tensors, arithmetic operations with tensors, storages).

# Tasks

In [1]:
import torch

Task 1. Create a tensor from the list(range(9)). Predict and check what size, offset and stride it has.

In [2]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
print('Shape: ', a.shape)
print('Offset: ', a.storage_offset())
print('Stride: ', a.stride())

Shape:  torch.Size([9])
Offset:  0
Stride:  (1,)


Task 2. Create a tensor b = a.view (3, 3). And calculate the value of b [1, 1].

In [4]:
b = a.view (3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
b[1, 1]

tensor(4)

Task 3. Create a tensor c = b [1:, 1:]. Predict and check what size, offset and stride it has.

In [6]:
c = b [1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [7]:
print('Shape: ', c.shape)
print('Offset: ', c.storage_offset())
print('Stride: ', c.stride())

Shape:  torch.Size([2, 2])
Offset:  4
Stride:  (3, 1)
